### PR TITLE
add resource providers for powershell package managment

### PR DESCRIPTION
**Pull request by trevorghess**
Manually rebased changes, resubmitting PR

### CODE REVIEW

**Comment by vinyar** [comment]
nice PR. Massive, but very nice functionality. Some of the stuff in there can be carved out into separate  tiny PRs. Like the not_if stuff for powershell5 is awesome.

**Comment by jugatsu** [comment]
@tas50 I think this PR should be closed in favor of build-in `powershell_package` provider.

**Comment by stuartpreston** [comment]
@trevorghess I'm closing this for now, mainly due to age and the PowerShell 5 bits should be working in core now.  We can open something new if we need to.

**Comment by smurawski** [comment]
There's still space for some helpers to get the nuget bits in place for offline scenarios, but yeah, this thing is way old.

**Pull request closed without merging**
