### PR TITLE
Change version to 5.1 in comments in powershell5 recipe

### PR DESCRIPTION
**Pull request by jugatsu**
### Description

- Update powershell version to 5.1 in comments.

### CODE REVIEW

**Comment by stuartpreston** [comment]
@jugatsu Thanks for the effort, the maintainers will update the changelog using a changelog generator at release time.  We're still working through some build issues first but will get a release out asap.

**Comment by stuartpreston** [comment]
@jugatsu Actually I see you're squeezing in a change to the powershell 5 recipe.  Can you revert your commits involving CHANGELOG.md and force push and we'll get the rest merged.

**Comment by jugatsu** [comment]
@stuartpreston Done.

**Comment by tas50** [comment]
Thanks

**Pull request merged**
