### PR TITLE
initial appveyor.yml

### PR DESCRIPTION
**Pull request by smurawski**
Please review @chef-cookbooks/client-windows and @chef-cookbooks/powershell-cookbook-collaborators

### CODE REVIEW

**Comment by mwrock** [comment]
:+1:

**Comment by tas50** [comment]
Is there any reason to keep the travis status or keep these windows cookbooks enabled in Travis?

**Comment by trevorghess** [comment]
:+1:

**Comment by smurawski** [comment]
@tas50 I think we should keep travis, since it does catch where cross-platform tests break

**Pull request merged**
